name: Linting

permissions: read-all

on:
  pull_request: {}
  merge_group: {}

# Cancel previous runs of the same workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
